sudo: false
dist: trusty
language: bash
python:
  - "3.6"
  - "3.5"
  - "3.4"
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv
  - "mvn -f clonedcodecheckerplugin dependency:purge-local-repository clean"

before_script:
  - pip install -r requirements_travis.txt
  - pip install .
  - "mvn -f clonedcodecheckerplugin clean validate initialize"

script:
  - "mvn -f clonedcodecheckerplugin clean validate initialize verify jacoco:report"
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
