sudo: required
dist: trusty
services:
  - docker

matrix:
  include:

    - language: java
      before_install:
        - sh -e /etc/init.d/xvfb start - sleep 3
        - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv
        - "mvn -f clonedcodecheckerplugin dependency:purge-local-repository clean"
      install:
        - apt-get install python3-pip
        - python3 setup.py install --user
      script:
        - python3 setup.py install --user
        - "mvn -f clonedcodecheckerplugin clean validate initialize verify jacoco:report"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: python
      python: 3.6
      before_install:
        - sh -e /etc/init.d/xvfb start - sleep 3
        - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv
        - "mvn -f clonedcodecheckerplugin dependency:purge-local-repository clean"
      install:
        - pip install tox-travis
      # command to run tests
      script:
        - tox
        - pip install .
        - "mvn -f clonedcodecheckerplugin clean validate initialize verify jacoco:report"

      after_success:
        - bash <(curl -s https://codecov.io/bash)

env:
  global:
   - DISPLAY=:99.0
