sudo: required
dist: xenial
services:
  - xvfb
language: bash
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8

before_install:
  - sudo apt-get -y install maven
  - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv

before_script:
  - pip install -r requirements_travis.txt
  - pip install .
  - "mvn -f clonedcodecheckerplugin dependency:purge-local-repository clean validate initialize"

script:
  - "mvn -f clonedcodecheckerplugin clean validate initialize verify jacoco:report"
  - tox

matrix:
  include:
    - python: 3.6
    - python: 3.5
    - python: 3.4

after_success:
  - bash <(curl -s https://codecov.io/bash)
