language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tox-travis coveralls codecov
# command to run tests
script:
  - tox
  - coverage run tests/test_main.py

after_success:
  - coveralls
  - codecov
