sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - sh -e /etc/init.d/xvfb start - sleep 3
        - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv
      install:
        - pip install tox-travis ruamel.yaml==0.15.89 pytest pytest-cov coverage codecov mock
      # command to run tests
      script:
        - tox

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: java
      before_script:
        - sh -e /etc/init.d/xvfb start - sleep 3
        - "mvn -f clonedcodecheckerplugin dependency:purge-local-repository clean"
      # command to run tests
      script:
        - "mvn -f clonedcodecheckerplugin initialize verify jacoco:report"

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: bash
      script:
        - "sudo docker build -t targetbuild ."

env:
  global:
   - DISPLAY=:99.0
