sudo: false
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tox-travis codecov
# command to run tests
script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
