sudo: required
dist: xenial
services:
  - xvfb
language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"

before_install:
  - sudo apt-get -y install maven
  - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv

before_script:
  - pip install -r requirements_travis.txt
  - pip install .
  - "mvn -f clonedcodecheckerplugin dependency:purge-local-repository clean validate initialize"

script:
  - "mvn -f clonedcodecheckerplugin clean validate initialize verify jacoco:report"
  - tox

matrix:
  include:
    - jdk: "openjdk7"
    - jdk: "openjdk8"
    - jdk: "oraclejdk7"
    - jdk: "oraclejdk8"

after_success:
  - bash <(curl -s https://codecov.io/bash)
