sudo: required
dist: xenial
services:
  - xvfb
language: java

before_install:
  - sudo apt-get -y install maven
  - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv

before_script:
  - "mvn -f clonedcodecheckerplugin dependency:purge-local-repository clean validate initialize"

script:
  - pip install . --user
  - "mvn -f clonedcodecheckerplugin clean validate initialize verify jacoco:report"
  - tox

matrix:
  include:
    - jdk: "openjdk9"
    - jdk: "openjdk10"
    - jdk: "openjdk11"
    - jdk: "openjdk12"
    - jdk: "openjdk13"
    - jdk: "oraclejdk9"
    - jdk: "oraclejdk10"
    - jdk: "oraclejdk11"
    - jdk: "oraclejdk12"
    - jdk: "oraclejdk13"

after_success:
  - bash <(curl -s https://codecov.io/bash)
