sudo: required
services:
  - docker
language: python
python:
  - "3.6"

before_install:
  - git clone --depth 1 https://github.com/opencv/opencv.git /home/travis/build/mzurzolo/opencv
  - sudo service docker restart
  - sleep 5
  - sudo docker build --tag local/centos7app .
  - sleep 5
  - sudo service docker restart

install:
  - pip install coverage codecov
# command to run tests
script:
  - sudo docker run -iv "/home:/home" local/centos7app /bin/sh -c "cd home/travis/build/mzurzolo/clonedCodeChecker ; python3 -m venv py37 ; source py37/bin/activate ; pip install -r requirements_travis.txt ; tox"

after_success:
  - bash <(curl -s https://codecov.io/bash)
